_commit: v0.0.1-53-g106b5fb
_src_path: https://github.com/jevangoh/q6taaj04do99vgf9cog0gurq6.git
minimum_python_version: "3.14"
orcid: 0009-0000-2958-6605
orcid_family_name: Goh
orcid_given_name: Kheng Xi Jevan
owner_email: javerngoh@gmail.com
owner_name: Jevan Goh
project_description: custom python std logger
project_id: v3ujgujq4i6tl12ekdt67jlrj
python_type: class
