repos:
  - repo: local
    hooks:
      - id: pixi-install
        name: pixi-install
        entry: pixi install
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        entry: pixi run -e dev ruff check --fix
        language: system
        types_or: [python, pyi]
        pass_filenames: true

      - id: ruff-format
        name: ruff-format
        entry: pixi run -e dev ruff format
        language: system
        types_or: [python, pyi]
        pass_filenames: true

      - id: format-documents
        name: format-documents
        entry: pixi run -e dev format_documents
        language: system
        pass_filenames: true

      - id: check-for-drift
        name: check-for-drift
        entry: git diff --exit-code
        language: system
        pass_filenames: false
